x-cassandra: &cassandras
    CASSANDRA_CLUSTER_NAME: testCluster
    CASSANDRA_SEEDS: cassandra1
    CASSANDRA_START_RPC: true
    CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch

x-expose: &exposes
    - "7000" # intra-node communication
    - "7001" # TLS intra node communication
    - "7199" # JMX
    - "9042" # CQL
    - "9142" # CQL TLS
    - "9160" # Thrift

services:
    cassandra1:
        image: cassandra:latest
        expose: *exposes
        # "host-port:container-port"
        environment: 
            <<: *cassandras
            CASSANDRA_DC: DC1
        ports:
            - "9042:9042"
        volumes:
            - "/Users/jamesroot/AAAroot/Course notes/Aalto Big Data Platforms/assignment-1-101699682/test:/test"

    cassandra2:
        image: cassandra:latest
        expose: *exposes
        environment: 
            <<: *cassandras
            CASSANDRA_DC: DC1
        ports:
            - "9043:9042"
        depends_on: 
            cassandra1:
                condition: service_started
                restart: true

    cassandra3:
        image: cassandra:latest
        expose: *exposes
        environment: 
            <<: *cassandras
            CASSANDRA_DC: DC1
        ports:
            - "9044:9042"
        depends_on: 
            cassandra1:
                condition: service_started
                restart: true