x-cassandra: &cassandras
    CASSANDRA_CLUSTER_NAME: testCluster
    CASSANDRA_SEEDS: cassandra1
    HEAP_NEWSIZE: 1M
    MAX_HEAP_SIZE: 512M
    CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch

x-expose: &exposes
    - "7000" # intra-node communication
    - "7001" # TLS intra node communication
    - "7199" # JMX
    - "9042" # CQL
    - "9142" # CQL TLS
    - "9160" # Thrift

services:
    cassandra1:
        image: cassandra:latest
        expose: *exposes
        # "host-port:container-port"
        ports:
            - "9042:9042"

    cassandra2:
        image: cassandra:latest
        expose: *exposes
        ports:
            - "9043:9042"
        

    cassandra3:
        image: cassandra:latest
        expose: *exposes
        ports:
            - "9044:9042"